### PR TITLE
Read the offset in the correct way

### PR DESCRIPTION
**Pull request by Gsantomaggio**
Fixes https://github.com/qweeze/rstream/issues/117

### CODE REVIEW

**Comment by Gsantomaggio** [comment]
@kyrylokovalenko you are right it was a bug. 

Do you have a chance to test this PR? It solves the problem

**Comment by kyrylokovalenko** [comment]
Hi @Gsantomaggio, now code from #117 works fine, but if I set `offset_specification` in subscribe call like this:
```python
    await consumer.subscribe(
        stream=STREAM,
        callback=on_message,
        decoder=amqp_decoder,
        offset_specification=ConsumerOffsetSpecification(OffsetType.OFFSET, 50)
    )
```
I receive following output:
```console
Got message: hello: 50 from stream my-test-stream, offset 32
Got message: hello: 51 from stream my-test-stream, offset 33
Got message: hello: 52 from stream my-test-stream, offset 34
Got message: hello: 53 from stream my-test-stream, offset 35
Got message: hello: 54 from stream my-test-stream, offset 36
...
...
Got message: hello: 93 from stream my-test-stream, offset 75
Got message: hello: 94 from stream my-test-stream, offset 76
Got message: hello: 95 from stream my-test-stream, offset 77
Got message: hello: 96 from stream my-test-stream, offset 96
Got message: hello: 97 from stream my-test-stream, offset 97
Got message: hello: 98 from stream my-test-stream, offset 98
Got message: hello: 99 from stream my-test-stream, offset 99
```

**Comment by kyrylokovalenko** [comment]
Maybe line 275 of consumer.py
```python
offset = frame.chunk_first_offset
```
should be
```python
offset = subscriber.offset
```
?

It seems to solve this issue.

**Comment by Gsantomaggio** [comment]
@kyrylokovalenko ok it should be okay now! I'd need to add some test

**Comment by kyrylokovalenko** [comment]
@Gsantomaggio yeah, works as intended, many thanks!

**Review by DanielePalaia — APPROVED** [review]

**Pull request merged**
