### PR TITLE
fix(client): Fix cleanup of Client._waiters dict

### LINKED ISSUE #125: Memory Leak in Client
The implementation of Client.waiters is a `defaultdict(set)`, each waiter will only be poped out from the `set` when it completes, while the underlying set will still occupy memory. Similarly, within the `_listener` task, after a frame is read, `defaultdict` creates a `set` internally when calling `waiters[key]` with the key not in waiters,  which is useless but has not been cleaned up.

### PR DESCRIPTION
**Pull request by qweeze**
fixes #125

### CODE REVIEW

**Review by DanielePalaia — APPROVED** [review]
Thanks!

**Comment by garvenlee** [comment]
In addition, function `wait_frame` also causes this bug.

**Comment by qweeze** [comment]
> In addition, function wait_frame also causes this bug.

Do you mean creating a set in `self._waiters[_key].add(fut)` ? But this is intentional - this keys will either be deleted from `_waiters` in `_listener`, or the future will time out, and an exception will be raised.

**Comment by garvenlee** [comment]
if the waiter is timeout, its callback will discard itself from the `self._waiters[key]`, but the underlaying set still exists?

**Comment by qweeze** [comment]
>  but the underlaying set still exists?

Yes, but I didn't consider it a big issue because it only happens when the app crashes, and recovery would require re-instantiating Client anyway, so at this point we don't care about memory. But I see your point now, and I agree it's better to not to leave any dangling references anyway

> Each frame has a unique correlation_id, so the waiter_key is also unique

According to protocol, one-way messages (commands, i.e. `Deliver`) don't have `correlation_id`. So basically storing waiters in a set allows having multiple concurrent calls to `wait_frame` for a single command.

But as I can see, currently this is not used in the project. So I think we can simplify this structure, get rid of sets altogether and make it a plain `dict[key, Future]` But only if we're sure that we won't need this "multiple waiters" functionality - perhaps @Gsantomaggio and @DanielePalaia can confirm that is redundant

**Comment by garvenlee** [comment]
> it only happens when the app crashes, and recovery would require re-instantiating Client anyway

Yes, it is. And note that `_waiters` is only used in `sync_request`, where `corr_id_seq` is used to guarantee the uniqueness. So just make `_waiters` a plain dict, and it’s also possible to simplify `_handlers` as [here](https://github.com/qweeze/rstream/issues/132).

**Comment by qweeze** [comment]
Ok, made `waiters` a plain dict

> it’s also possible to simplify _handlers

I suggest to work on this in a next PR

**Comment by qweeze** [comment]
@Gsantomaggio do you mind if I merge this?

**Comment by Gsantomaggio** [comment]
it is ok with me! thank you @qweeze

**Review by Gsantomaggio — APPROVED** [review]

**Pull request merged**
