### PR TITLE
Test encoding optimiations

### PR DESCRIPTION
**Pull request by Gsantomaggio**

### CODE REVIEW

**Comment by DanielePalaia** [comment]
HI @qweeze, we are trying to do some general optimization work on the project and we would like also to review the branch you originally posted here: https://github.com/qweeze/rstream/issues/30

The code is running and it is saving us few seconds over millions of messges but It seems like there an issue importing _FIELD of the dataclasses module. Can you help us going through this? Thanks!

**Comment by qweeze** [comment]
Hi @DanielePalaia 

I re-implemented this optimization with dataclasses in a safer manner [here](https://github.com/qweeze/rstream/compare/feat/encoding-optimizations?expand=1). Didn't benchmark it though, but it shouldn't be much slower than the version using `_FIELD`. Hope this helps!

**Comment by Gsantomaggio** [comment]
Thanks @qweeze 
I tried the branch and:
```
(.venv) ➜  rstream git:(feat/encoding-optimizations) python docs/examples/basic_producers/producer_send_batch_binary.py
Sent 1000000 messages in 9.1153 seconds. 109706.0540 messages per second
```

Master:
```
(.venv) ➜  rstream git:(master) python docs/examples/basic_producers/producer_send_batch_binary.py
Sent 1000000 messages in 7.7188 seconds. 129553.2735 messages per second
```

So the current implementation seems to be faster.

**Comment by qweeze** [comment]
@Gsantomaggio I added some more fixes, and run the same benchmark. It showed ~20% speedup (6.8 vs 5.6 seconds). Can you try it again on updated branch?

**Comment by Gsantomaggio** [comment]
@qweeze seems to be better. I don't understand the build problem here https://github.com/qweeze/rstream/actions/runs/5572702984/jobs/10179031187

**Comment by Gsantomaggio** [comment]
closed in favour of https://github.com/qweeze/rstream/pull/100

**Pull request closed without merging**
